# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
    flutter-package:
        name: animated_icon_button
        environment:
            flutter: dev
        scripts:
            - flutter packages pub get
            - flutter test