name: animated_icon_button
description: Flutter package to create custom animated IconButton. Includes all available icons. Based on native IconButton.
version: 0.2.0
author: youngfrezyx@gmail.com
homepage: https://github.com/Frezyx/animated_icon_button

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
