name: animated_icon_button
description: Flutter package to create custom animated IconButton. Includes all available icons. Based on native IconButton.
version: 1.1.0
homepage: https://github.com/Frezyx/animated_icon_button

environment:
  sdk: '>=3.2.0 <3.10.0'
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
